language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.5.0.1
  - MAGENTO_VERSION=magento-ce-1.6.0.0
  - MAGENTO_VERSION=magento-ce-1.6.1.0
  - MAGENTO_VERSION=magento-ce-1.6.2.0
  - MAGENTO_VERSION=magento-ce-1.7.0.0
  - MAGENTO_VERSION=magento-ce-1.7.0.1
  - MAGENTO_VERSION=magento-ce-1.7.0.2
  - MAGENTO_VERSION=magento-ce-1.8.0.0
  - MAGENTO_VERSION=magento-ce-1.8.1.0
  - MAGENTO_VERSION=magento-ce-1.9.0.0
  - MAGENTO_VERSION=magento-ce-1.9.0.1
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  global:
    secure: RsXdjcvJXbnXH3O53h/8rVx6kdOZydY+f/2mI4HdAR9Yu9VL15VMcRClQnaHayJa1hzsWgAX32AFYxNl0iRz8NPWAGki2OkGmsRhhg8fyH1HD3KPITyRyoTb//yogNCi77/SHbFJzWFi/V7RXqqXTInTvwWU/UBmhjiE3if3LNk=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: bPy6G6sc8iNpGQUwmKiriaUkVpL7T+6BPIWFitBuGIAqigAEgvkaHzdNo0ZQQNvhlBQBqT897kPSkAsMWKsqkxX8WAmh8Y1DzRx+Vb1ETzYjKMQ4MbXVy6e7zElEZ94ULxyT58XU+R3pyUeQ3AifFOJeNYzVn9YFpNhehW59Gs4=
