language: php
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/bin
    - $HOME/.n98-magerun/modules
    - $HOME/.cache/magento
php:
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - php: 5.6
    env: MAGENTO_VERSION=ce-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=ce-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_DevTools
  - secure: nhCg4z1BHuleaDp/V7sLiAWOwKBX+B55HiYzzU9V25nlbc3jDCXbAHu4m4zt/LrSeGDrnF+jIZgPMFxg03eyuvnner47t1ub0aY9tL8d7EiMB6Y9/QsbjXstmnQGr2ReP2YyeN/EWRST0CNODAXivdnTS5Vzq+XHlPlyccQ+JP0=
  - secure: Pcsb+ORGxpTQeVnI2bdvQQ9UoDsKs/PT9xqBto2htDnRmaWvhKtFC5Whh0U+5iozMJON+tEm4Pz2kDSZvaboueWlkFLiJif7uWSPl2gljTwn3Sw1pFAb2tUFzIt+UJsot2wNpYHgI94vM4iJEaavYmyFtqKMceRmDZanH/NtdC4=
  matrix:
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
  - MAGENTO_VERSION=ce-1.8.1.0
  - MAGENTO_VERSION=ce-1.7.0.2
  - MAGENTO_VERSION=ce-1.6.2.0
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: F8ZESLTfEbOaBgVNpc23EEIXN4lBFeapaMfgoHdvdah7K1nMwXpXXvAN9oqc2uH0g740Dk2K5FUhjxBadcVjmKDtKwqy2E6YL9sqjzEWbpBv6Vets131+YIchr4mZv5srO2wRtxAA7GxoXsrmgFQa43u6zCyOsEVz3Xp6b/iUfE=
notifications:
  slack:
    secure: Zx1rF2vKudUoRABd+tjk+pd9RHMLx3E8BZaTDJFuZyeQpUHW9dp7ktDHK4/C6yWMnaEAgGoI0J8TJ/mTnOmeDi1OXw7RteiR8gpaP5u8j8DsC4gqutqHyYKVeNUWatYgtoz2f8eSdpHkNPJlGi9Y7tJxFElgzksLlgBkzF4wE5M=
