<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(0, 'level-top') ?>
<?php if ($_menu): ?>
    <div class="nav-container">
        <ul id="nav">
            <?php if (Mage::getStoreConfig('ffuenf_devtools/linkmanager/catalog_navigation_home_active')):
                $homeLabel = Mage::getStoreConfig('catalog_navigation_home_label';
                $isHomeActive = trim($this->helper('core/url')->getCurrentUrl(), '/') == trim(Mage::getUrl(), '/') ? ' active' : null;
            ?>
                <li class="first<?php echo $isHomeActive; ?>">
                    <a href="<?php echo Mage::getUrl(); ?>" class="">
                        <span><?php echo $homeLabel; ?></span>
                    </a>
                </li>
            <?php endif; ?>
            <?php echo $_menu ?>
        </ul>
    </div>
<?php endif ?>
