<div class="content-header">
    <table cellspacing="0">
        <tbody>
            <tr>
                <td style="width:50%;"><h3 class="icon-head head-diagnostic-checkModules"><?= $this->__('Resave Products'); ?></h3></td>
                <td class="form-buttons"></td>
            </tr>
        </tbody>
    </table>
</div>
<button id="button" class="scalable" onclick="setLocation('<?= $this->getUrl('devtools/resave_products/run'); ?>')" type="adminhtml/widget_button" title="<?= Mage::helper('ffuenf_devtools')->__('Resave Products'); ?>"><span><span><span><?= Mage::helper('ffuenf_devtools')->__('Resave Products'); ?></span></span></span></button>
